# ICON
#
# ---------------------------------------------------------------
# Copyright (C) 2004-2026, DWD, MPI-M, DKRZ, KIT, ETH, MeteoSwiss
# Contact information: icon-model.org
# See AUTHORS.TXT for a list of authors
# See LICENSES/ for license information
# SPDX-License-Identifier: BSD-3-Clause
# ---------------------------------------------------------------

spec:
  inputs:
    add-basic-stage:
      type: boolean
      default: true
      description: add the basic stage to the pipeline
    add-unit-stage:
      type: boolean
      default: true
      description: add the unit stage to the pipeline
    add-functional-stage:
      type: boolean
      default: true
      description: add the functional stage to the pipeline
    add-system-stage:
      type: boolean
      default: true
      description: add the system stage to the pipeline
    add-external-stage:
      type: boolean
      default: true
      description: add the external stage to the pipeline

---

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "schedule"
      auto_cancel:
        on_new_commit: none

stages:
  - basic
  - unit
  - functional
  - system
  - external
  - optional

default:
  interruptible: true

include:
  - local: .gitlab/ci/basic.yml
    rules:
      - if: '"$[[ inputs.add-basic-stage ]]" == "false"'
        when: never
  - local: .gitlab/ci/unit/icon.yml
    rules:
      - if: '"$[[ inputs.add-unit-stage ]]" == "false"'
        when: never
      - if: $CI_PROJECT_PATH == "icon/icon-model"
        when: never
      - if: $CI_PIPELINE_SOURCE == "web"
      - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        changes:
          - "*.in"
          - .gitlab/ci/unit/icon.yml
          - config/dkrz/*
          - configure
          - externals/**/*
          - src/**/*
          - support/**/*
          - test/unit-tests/**/*
          - utils/**/*
  - local: .gitlab/ci/unit/ragnarok.yml
    rules:
      - if: '"$[[ inputs.add-unit-stage ]]" == "false"'
        when: never
      - if: $CI_PROJECT_PATH == "icon/icon-model"
        when: never
      - if: $CI_PIPELINE_SOURCE == "web"
      - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        changes:
          - .gitlab/ci/unit/ragnarok.yml
          - ragnarok/**/*
  - local: .gitlab/ci/functional/nwp-microphysics.yml
    rules:
      - if: '"$[[ inputs.add-functional-stage ]]" == "false"'
        when: never
      - if: $CI_PROJECT_PATH == "icon/icon-model"
        when: never
      - if: $CI_PIPELINE_SOURCE == "web"
      - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        changes:
          - .gitlab/ci/functional/nwp-microphysics.yml
          - externals/fortran-support
          - externals/iconmath
          - externals/probtest
          - src/atm_phy_schemes/mo_lookup_tables_constants.f90
          - src/atm_phy_schemes/mo_thdyn_functions.f90
          - src/atm_phy_schemes/mo_2mom_mcrph_types.f90
          - src/atm_phy_schemes/mo_2mom_mcrph_setup.f90
          - src/configure_model/mo_2mom_mcrph_config.f90
          - src/granules/microphysics_1mom_schemes/**/*
          - src/shared/mo_kind.f90
          - src/shared/mo_physical_constants.f90
          - src/shared/mo_impl_constants.f90
          - src/shared/mo_impl_constants_grf.f90
          - test/microphysics_1mom_schemes/**/*
  - local: .gitlab/ci/system.yml
    rules:
      - if: '"$[[ inputs.add-system-stage ]]" == "false"'
        when: never
      - if: $CI_PROJECT_PATH == "icon/icon-model"
        when: never
      - when: always
  - local: .gitlab/ci/nightly/*.yml
    rules:
      - if: '"$[[ inputs.add-system-stage ]]" == "false"'
        when: never
      - if: $CI_PROJECT_PATH == "icon/icon-model"
        when: never
      - if: $CI_PIPELINE_SOURCE == "web"
      - if: $CI_PIPELINE_SOURCE == "schedule" && $ICON_CI_TEST_SCHEDULE == "nightly"
  - local: .gitlab/ci/cscs/santis.yml
    rules:
      - if: '"$[[ inputs.add-external-stage ]]" == "false"'
        when: never
      - if: $CI_PROJECT_PATH == "icon/icon-model"
        when: never
      - if: $CI_PIPELINE_SOURCE == "web"
      - if: $CI_PIPELINE_SOURCE == "schedule"
      - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        changes:
          - .gitlab/ci/cscs/**/*
          - scripts/cscs_ci/**/*
      - if: >-
          $CI_PIPELINE_SOURCE == "merge_request_event" &&
            $CI_MERGE_REQUEST_PROJECT_PATH != "icon/icon-mpim"
