# ICON
#
# ---------------------------------------------------------------
# Copyright (C) 2004-2026, DWD, MPI-M, DKRZ, KIT, ETH, MeteoSwiss
# Contact information: icon-model.org
#
# See AUTHORS.TXT for a list of authors
# See LICENSES/ for license information
# SPDX-License-Identifier: BSD-3-Clause
# ---------------------------------------------------------------

# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

import os

import pydata_sphinx_theme

# -- Project information -----------------------------------------------------

project = "ICON"
copyright = "2026, The ICON Partners"
author = "ICON"
html_favicon = "_static/faviconICON.ico"

extensions = [
    "myst_parser",
    "sphinx_design",  # , 'sphinx_favicon' #Markdown adjustments
]

myst_heading_anchors = 4

myst_enable_extensions = [
    "deflist",
    "colon_fence",
    "substitution",
]

myst_substitutions = {"release": "2025.10-2"}

# Important: This needs to be updated with a new release.
# Several URLs are built using this string
if os.getenv("CI_PIPELINE_SOURCE", None) == "merge_request_event":
    project_url = os.getenv("CI_MERGE_REQUEST_SOURCE_PROJECT_URL")
    commit_ref_name = os.getenv("CI_MERGE_REQUEST_SOURCE_BRANCH_NAME")
else:
    project_url = os.getenv(
        "CI_PROJECT_URL", "https://gitlab.dkrz.de/icon/icon-model"
    )
    commit_ref_name = os.getenv(
        "CI_COMMIT_REF_NAME",
        "icon-" + myst_substitutions["release"] + "-public",
    )

myst_substitutions["base_url"] = project_url + "/-/blob/" + commit_ref_name

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# html_static_path = ["_static"]

# The suffix(es) of source filenames.
source_suffix = ".md"

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"


#    These values determine how to format the current date, used as the replacement for |today|.
today_fmt = "%b %d %y at %H:%M"

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme = 'alabaster'
# html_theme = 'sphinx_rtd_theme'

# html_theme_options = {
#    "collapse_navigation" : False
# }

html_theme = "pydata_sphinx_theme"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.

html_theme_options = {
    "body_max_width": None,
    "navbar_align": "left",
    "show_prev_next": False,
    "gitlab_url": "https://gitlab.dkrz.de/icon/icon-model",
    "footer_start": ["imprint", "copyright", "sphinx-version"],
    "icon_links": [
        {
            "name": "icon-model.org",
            "url": "https://icon-model.org",
            "icon": "fas fa-home",
        },
    ],
    "logo": {
        "image_light": "_static/ICON_logo_black.svg",
        "image_dark": "_static/ICON_logo_white.svg",
    },
}

html_context = {"default_mode": "light"}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]
html_css_files = ["theme_overrides.css", "colors.css"]

# If true, the reST sources are included in the HTML build as _sources/<name>.
html_copy_source = False

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#'search-field'
# html_sidebars = {}
html_sidebars = {
    "secondary_sidebar_items": ["page-toc", "edit-this-page", "sourcelink"],
    "**": [],
    # "index": ['hello.html', 'searchbox.html' , 'sidebar-nav-bs.html','localtoc.html',], # 'globaltoc.html'
}

# -- Options for LaTeX syntax rendering

mathjax_path = "tex-mml-chtml.js"

# -- Options for LaTeX output ------------------------------------------------

latex_elements = {}
