#!/bin/bash

# ICON
#
# ------------------------------------------
# Copyright (C) 2004-2025, DWD, MPI-M, DKRZ, KIT, ETH, MeteoSwiss
# Contact information: icon-model.org
# See AUTHORS.TXT for a list of authors
# See LICENSES/ for license information
# SPDX-License-Identifier: BSD-3-Clause
# ------------------------------------------

set -eu

MY_DIR=$(cd "$(dirname "$0")"; pwd)
ICON_DIR=$(cd "${MY_DIR}/../.."; pwd)

if [ ! -z "${BB_NAME}" ]; then
  set -x
  set MPI_LAUNCH='srun -A mh0156 -p compute -N 1'
else
  # Setting MPI_LAUNCH to an empty string is not the same as not setting it at
  # all for the configure script of YAC. With the following, we make sure that
  # we do not pass any additional arguments:
  set dummy; shift
fi

${ICON_DIR}/config/dkrz/levante.cpu.nvhpc-24.11 --disable-openmp --enable-ecrad "$@"

if [ ! -z "${BB_NAME}" ] ; then
  MAKE_PROCS=22
  echo "MAKE_PROCS=${MAKE_PROCS}"
else
  MAKE_PROCS=8
fi

make -j ${MAKE_PROCS}
