#!/bin/bash

# ICON
#
# ------------------------------------------
# Copyright (C) 2004-2025, DWD, MPI-M, DKRZ, KIT, ETH, MeteoSwiss
# Contact information: icon-model.org
# See AUTHORS.TXT for a list of authors
# See LICENSES/ for license information
# SPDX-License-Identifier: BSD-3-Clause
# ------------------------------------------

set -eu

MY_DIR=$(cd "$(dirname "$0")"; pwd)
ICON_DIR=$(cd "${MY_DIR}/../.."; pwd)

if [ ! -z "${BB_NAME}" ]; then
  set -x
  set MPI_LAUNCH='srun -A mh0156 -p compute -N 1'
else
  # Setting MPI_LAUNCH to an empty string is not the same as not setting it at
  # all for the configure script of YAC. With the following, we make sure that
  # we do not pass any additional arguments:
  set dummy; shift
fi

# TODO: remove the acx_cv_fc_have_c_loc_of_slice argument below once we either
# switch to NVHPC 24.11 or to a version of YAXT with the extended NVHPC
# workaround: https://gitlab.dkrz.de/dkrz-sw/yaxt/-/commit/ac760200edc8c6168f8db1562b4774e9d1788a55
${ICON_DIR}/config/dkrz/levante.gpu.nvhpc --disable-openmp --enable-ecrad --enable-testbed --enable-yaxt acx_cv_fc_have_c_loc_of_slice=no "$@"

if [ ! -z "${BB_NAME}" ] ; then
  MAKE_PROCS=22
  echo "MAKE_PROCS=${MAKE_PROCS}"
else
  MAKE_PROCS=8
fi

make -j ${MAKE_PROCS}
