#!/bin/bash

# ICON
#
# ------------------------------------------
# Copyright (C) 2004-2025, DWD, MPI-M, DKRZ, KIT, ETH, MeteoSwiss
# Contact information: icon-model.org
# See AUTHORS.TXT for a list of authors
# See LICENSES/ for license information
# SPDX-License-Identifier: BSD-3-Clause
# ------------------------------------------

set -euo pipefail

ulimit -s unlimited

unset CDPATH
script_dir=$(cd "$(dirname "$0")"; pwd)
icon_dir=$(cd "${script_dir}/../.."; pwd)

# These paths are critical to proper loggin by buildbot
ve_dir="${icon_dir}/build/ve"
vh_dir="${icon_dir}/build/vh"

if test -n "${BB_NAME-}"; then
  job_count=22
else
  job_count=8
fi

unset MAKEFLAGS
makeflags="--jobs=${job_count} V=1"

set -x

make ${makeflags} -f - <<_EOF
GNUMAKEFLAGS= --no-print-directory --output-sync=line
SHELL= /bin/bash
.PHONY: all host vector
all: host vector
host:
	@mkdir -p ${vh_dir}
	# configuring host
	cd ${vh_dir} && ${icon_dir}/config/dkrz/aurora.VH.gcc_mpi-3.4.0 --disable-openmp
	set -o pipefail; cd ${vh_dir} && \$(MAKE) |& tee make.log
vector:
	@mkdir -p ${ve_dir}
	# configuring vector
	cd ${ve_dir} && ${icon_dir}/config/dkrz/aurora.VE.nfort-5.0.1_mpi-3.4.0 --disable-openmp
	set -o pipefail; cd ${ve_dir} && \$(MAKE) |& tee make.log
_EOF

# Copy the generated system description because the buildbot-scripting needs it:
cat ${ve_dir}/run/set-up.info
cp -v ${ve_dir}/run/set-up.info ${icon_dir}/run
