#!/bin/bash

# ICON
#
# ------------------------------------------
# Copyright (C) 2004-2025, DWD, MPI-M, DKRZ, KIT, ETH, MeteoSwiss
# Contact information: icon-model.org
# See AUTHORS.TXT for a list of authors
# See LICENSES/ for license information
# SPDX-License-Identifier: BSD-3-Clause
# ------------------------------------------

set -eu

script_dir=$(cd "$(dirname "$0")"; pwd)
icon_dir=$(cd "${script_dir}/../.."; pwd)

if [ ! -z "${BB_NAME-}" ] ; then
  export MAKEFLAGS='-j22'
else
  export MAKEFLAGS='-j8'
fi

${icon_dir}/config/csc/lumi.gpu.cce
make V=1
