#! /usr/bin/env python
from fileinput import input
from datetime import datetime

for line in input():
    print(datetime.now().strftime("%FT%T.%f")[:-3], line,
          sep=': ', end='', flush=True)
