#!/bin/bash

# ICON
#
# ---------------------------------------------------------------
# Copyright (C) 2004-2025, DWD, MPI-M, DKRZ, KIT, ETH, MeteoSwiss
# Contact information: icon-model.org
# See AUTHORS.TXT for a list of authors
# See LICENSES/ for license information
# SPDX-License-Identifier: BSD-3-Clause
# ---------------------------------------------------------------

# ----------------------------------------------------------------------------
#PBS -q sx_norm
#PBS -l elapstim_req=00:35:00
#PBS --venode=3          # Run up to 3 * 8 = 24 MPI jobs
#PBS --venum-lhost=8     # Number of VE per logical host
#PBS --use-hca=2         # Number of HCA per logical host
#PBS -T necmpi_hydra
#PBS -j o
#PBS -o LOG.exp.check_externals_DWD.run.run.o
# ----------------------------------------------------------------------

# for PBS change to directory where job was submitted
# (without this job is started in HOME)
if [[ -n ${PBS_O_WORKDIR} ]] ; then
  cd ${PBS_O_WORKDIR} # This is ${ICON_DIR}/run under buildbot.
fi

# We cannot rely on the contents of the 'exp.check_externals_DWD.run.status.2'
# file produced by the scheduler because it might be empty if the time limit for
# the job is exceeded, which leads to a false positive result of the test.
# Instead, we create 'exp.check_externals_DWD.run.final_status', which has
# higher priority for the Buildbot. We write a non-zero exit code to the file,
# which will indicate a failure if the code below does not have enough time to
# finish:
echo '255' > exp.check_externals_DWD.run.final_status

unset MAKEFLAGS

set -x

# Build the tests with the highest level of parallelism (limited by the number
# of the host CPU cores on one node) and then run them with a smaller number of
# jobs (limited by the number of the vector engine cores on all nodes):
time make -C ../vector --jobs=24 --keep-going --no-print-directory --output-sync=target V=1 TESTS= check-bundled && \
  time make -C ../vector --jobs=4 --keep-going ICON_VERBOSE_TESTS=1 ICON_COLOR_TESTS=always check-bundled

# Save the exit code of the 'make check-bundled' command:
exitcode=$?

set +x

# Overwrite the status file with the real exit code:
echo "${exitcode}" > exp.check_externals_DWD.run.final_status

# Exit with the exit code of the 'make check-bundled' command:
exit ${exitcode}
