! ICON
!
! ---------------------------------------------------------------
! Copyright (C) 2004-2025, DWD, MPI-M, DKRZ, KIT, ETH, MeteoSwiss
! Contact information: icon-model.org
!
! See AUTHORS.TXT for a list of authors
! See LICENSES/ for license information
! SPDX-License-Identifier: BSD-3-Clause
! ---------------------------------------------------------------

! This module provides methods for reading arbitrarily distributed data from a
! NetCDF file in a distributed way.
! This approach reduces memory consumption.

#include "omp_definitions.inc"
! -----------------------------------------------------------------------------
! MODULE: mo_read_netcdf_distributed
!
! Purpose
! -------
! Provide a reusable, distributed NetCDF read facility. The module implements:
!  - setup and usage of redistribution pattern from io decomposition
!    generated by mo_read_netcdf_distributed_base into the user decomposition
!
! Design overview
! ---------------
! * Read pattern:
!     1. Reading of data into a compact local buffer using
!        mo_read_netcdf_distributed_base
!     2. Use ICON communication patterns (exchange_data / t_comm_pattern) to
!        redistribute data into the ICON-internal decomposition.
!
! Example (pseudo-usage)
! ---------------------
!   integer :: ncid
!   type(t_distrib_read_data) :: iod(1)
!   ! Setup once for a global array length n_g and glb_index on each rank:
!   call setup_distrib_read(n_g, local_glb_index, iod(1))
!   ncid = distrib_nf_open(filename)
!   call distrib_read(ncid, 'varname', some_ptr_wrapper, iod)
!   call distrib_nf_close(ncid)
!   call delete_distrib_read(iod(1))
!
! -----------------------------------------------------------------------------

MODULE mo_read_netcdf_distributed

  USE mo_kind, ONLY: dp, sp
  USE mo_exception, ONLY: finish, message
  USE mo_mpi, ONLY: p_n_work, p_pe_work, p_bcast, p_comm_work, p_max
  USE ppm_extents, ONLY: extent
  USE mo_decomposition_tools, ONLY: t_glb2loc_index_lookup, &
    & init_glb2loc_index_lookup, set_inner_glb_index, &
    & deallocate_glb2loc_index_lookup, uniform_partition, &
    & partidx_of_elem_uniform_deco
  USE mo_communication, ONLY: t_comm_pattern, exchange_data, &
    & delete_comm_pattern
  USE mo_parallel_config, ONLY: nproma, idx_1d
  USE mo_communication_factory, ONLY: setup_comm_pattern
  USE fortran_support, ONLY: t_ptr_2d_dp, t_ptr_2d_int, t_ptr_2d_sp, &
    & t_ptr_3d_dp, t_ptr_3d_int, t_ptr_3d_sp, t_ptr_4d_dp, t_ptr_4d_int, &
    & t_ptr_4d_sp
  USE mo_read_netcdf_types, ONLY: t_distrib_read_data
  USE mo_read_netcdf_distributed_base, ONLY: &
    & distrib_nf_open => distrib_nf_open_base, &
    & distrib_nf_close => distrib_nf_close_base, &
    & distrib_nf_inq_varexists => distrib_nf_inq_varexists_base, &
    & distrib_inq_var_dims => distrib_inq_var_dims_base, &
    & distrib_read_get_owner, distrib_read_get_decomp, &
    & setup_distrib_read_base, delete_distrib_read_base, &
    & distrib_read_base

  IMPLICIT NONE
  PRIVATE

  CHARACTER(*), PARAMETER :: modname = 'mo_read_netcdf_distributed'

  PUBLIC :: distrib_read
  PUBLIC :: distrib_nf_open
  PUBLIC :: distrib_nf_inq_varexists
  PUBLIC :: distrib_nf_close
  PUBLIC :: setup_distrib_read
  PUBLIC :: delete_distrib_read
  PUBLIC :: t_distrib_read_data
  PUBLIC :: distrib_inq_var_dims
  PUBLIC :: idx_lvl_blk, idx_blk_time

  INTEGER, PARAMETER :: idx_lvl_blk = 2
  INTEGER, PARAMETER :: idx_blk_time = 3

  !modules interface-------------------------------------------
  !subroutines

CONTAINS

  ! -------------------------------------------
  ! setup_distrib_read(n_g, glb_index, io_data)
  ! -------------------------------------------
  ! Prepare data structures and communication pattern for distributed reads of
  ! a global 1-D array of length n_g (e.g. global number of cells).
  !
  ! Inputs:
  !  - n_g: length of the global array
  !  - glb_index(:): global indices of the points locally stored on this
  !                  process (may be empty)
  !
  ! Outputs / inout:
  !  - io_data: t_distrib_read_data to be used by distrib_read
  SUBROUTINE setup_distrib_read(n_g, glb_index, io_data)
    INTEGER, INTENT(in) :: n_g !< global array size
    INTEGER, ALLOCATABLE, INTENT(in) :: glb_index(:) !< global ids stored on
                                                     !< the local process
    TYPE(t_distrib_read_data), INTENT(inout) :: io_data
    INTEGER :: n, n_inner, i
    INTEGER, ALLOCATABLE :: owner(:)
    TYPE(t_glb2loc_index_lookup) :: glb2loc_index
    TYPE(extent) :: io_chunk

    ! setup basic read data
    CALL setup_distrib_read_base(n_g, io_data%basic_data_index)

    ! generate redistribution pattern io to user decomposition
    CALL distrib_read_get_owner(io_data%basic_data_index, glb_index, owner)
    io_chunk = distrib_read_get_decomp(io_data%basic_data_index)
    CALL init_glb2loc_index_lookup(glb2loc_index, n_g)
    n_inner = io_chunk%size
    IF (n_inner > 0) THEN
      CALL set_inner_glb_index( &
        glb2loc_index, (/(i + io_chunk%first - 1, i = 1, n_inner)/), &
        (/(i, i = 1, n_inner)/))
    END IF
    IF (ALLOCATED(glb_index)) THEN
      n = SIZE(glb_index)
    ELSE
      n = 0
    END IF
    CALL setup_comm_pattern( &
      n, owner(:), glb_index(:), glb2loc_index, n_inner, &
      (/(p_pe_work, i = 1, n_inner)/), glb2loc_index%inner_glb_index, &
      io_data%pat)
    CALL deallocate_glb2loc_index_lookup(glb2loc_index)
  END SUBROUTINE setup_distrib_read

  !-----------------------------
  ! delete_distrib_read(io_data)
  ! ----------------------------
  ! Deregister and free resources associated with io_data created by
  ! setup_distrib_read.
  SUBROUTINE delete_distrib_read(io_data)
    TYPE(t_distrib_read_data), INTENT(inout) :: io_data

    CALL delete_comm_pattern(io_data%pat)
    CALL delete_distrib_read_base(io_data%basic_data_index)
  END SUBROUTINE delete_distrib_read

  !-------------------------------------------------------------------------
  ! distrib_read(ncid, vname, vdata, iod, [,edim, dimo, start_ext_dim, end_ext_dim])
  ! -------------------------------------------------------------------------------
  ! Read variable `vname` from NetCDF file using mo_read_netcdf_distributed_base.
  ! All provided `iod` entries are expected to reference the same
  ! t_basic_distrib_read_data data structure. After reading the data is
  ! redistributed according to t_distrib_read_data array `iod(:)%pat`.
  ! This allows for the data to be redistributed more than once using different
  ! exchagen patterns.
  !
  ! Supported vdata types: t_ptr_2d_*, t_ptr_3d_*, t_ptr_4d_* (int, sp, dp).
  ! The routine reads the IO rank's assigned 1-D chunk into local buffers
  ! (io decomposition), applies blocking (1D -> 2D [nproma,blk]), and then
  ! uses exchange_data (communication pattern) to redistribute data according to
  ! t_distrib_read_data array `iod(:)%pat`. This allows for the data to be
  ! redistributed more than once using different exchagen patterns.
  !
  ! Optional parameters (edim, dimo, start_ext_dim, end_ext_dim) control how
  ! extra external dimensions (levels/time/blocks) map into the read ordering.
  ! See inline handling of idx_lvl_blk and idx_blk_time.
  SUBROUTINE distrib_read(ncid, vname, vdata, iod, &
    & edim, dimo, start_ext_dim, end_ext_dim)
    INTEGER, INTENT(IN) :: ncid
    CHARACTER(*), INTENT(IN) :: vname
    CLASS(*), INTENT(INOUT) :: vdata(:)
    TYPE(t_distrib_read_data), INTENT(IN) :: iod(:)
    INTEGER, INTENT(IN), OPTIONAL :: edim(:) !< extra dimensions
    INTEGER, INTENT(IN), OPTIONAL :: dimo !< dimension ordering
                                          !< (idx_blk_time or idx_lvl_blk)
    INTEGER, INTENT(IN), OPTIONAL :: start_ext_dim(:), end_ext_dim(:)
    INTEGER :: ish(3), osh(4), strt(3)
    TYPE(extent) :: io_chunk
    CHARACTER(*), PARAMETER :: routine = modname//"distrib_read"

    IF (SIZE(iod) == 0) RETURN
    IF (SIZE(vdata) < SIZE(iod)) CALL finish(routine, "var_data too small")
    IF (SIZE(iod) .GT. 1) THEN
      IF (.NOT.ALL(iod(2:)%basic_data_index .EQ. iod(1)%basic_data_index)) &
        & CALL finish(routine, "basic_data_index do not match")
    END IF
    io_chunk = distrib_read_get_decomp(iod(1)%basic_data_index)
    ish(:) = [io_chunk%size, 1, 1]
    osh(:) = [nproma, (ish(1)+nproma-1)/nproma, 1, 1]
    strt(:) = [io_chunk%first, 1, 1]
    IF (PRESENT(edim)) THEN
      IF (SIZE(edim) .EQ. 1) THEN
        IF (.NOT.PRESENT(dimo)) CALL finish(routine, "invalid arguments")
        SELECT CASE(dimo)
        CASE(idx_blk_time)
          osh(3) = edim(1)
        CASE(idx_lvl_blk)
          osh(3) = osh(2)
          osh(2) = edim(1)
        CASE DEFAULT
          CALL finish(routine, "invalid dim_order")
        END SELECT
        ish(2) = edim(1)
      ELSE IF (SIZE(edim) .EQ. 2) THEN
        osh(3) = osh(2)
        osh(2) = edim(1)
        osh(4) = edim(2)
        ish(2:3) = edim(1:2)
      END IF
      IF (PRESENT(start_ext_dim)) THEN
        IF (.NOT.PRESENT(end_ext_dim)) CALL finish(routine, "invalid arguments")
        IF (SIZE(edim) .NE. SIZE(start_ext_dim) .OR. SIZE(edim) .NE. SIZE(end_ext_dim)) &
          & CALL finish(routine, "invalid arguments")
        IF (ANY((end_ext_dim - start_ext_dim + 1) /= edim)) &
          & CALL finish(routine, "invalid arguments: edim /= end-start-1")
        strt(2:SIZE(edim)+1) = start_ext_dim(1:SIZE(edim))
      END IF
    END IF
    SELECT TYPE(vdata)
    TYPE IS(t_ptr_2d_dp)
      CALL read_multi_var_2ddp(vdata)
    TYPE IS(t_ptr_2d_sp)
      CALL read_multi_var_2dsp(vdata)
    TYPE IS(t_ptr_2d_int)
      CALL read_multi_var_2dint(vdata)
    TYPE IS(t_ptr_3d_dp)
      CALL read_multi_var_3ddp(vdata, dimo)
    TYPE IS(t_ptr_3d_sp)
      CALL read_multi_var_3dsp(vdata, dimo)
    TYPE IS(t_ptr_3d_int)
      CALL read_multi_var_3dint(vdata, dimo)
    TYPE IS(t_ptr_4d_dp)
      CALL read_multi_var_4ddp(vdata)
    TYPE IS(t_ptr_4d_sp)
      CALL read_multi_var_4dsp(vdata)
    TYPE IS(t_ptr_4d_int)
      CALL read_multi_var_4dint(vdata)
    CLASS DEFAULT
      CALL finish("distrib_read_multi_var", "un-recognized type")
    END SELECT
  CONTAINS

    SUBROUTINE read_multi_var_2dint(vd)
      TYPE(t_ptr_2d_int), INTENT(INOUT) :: vd(:)
      INTEGER :: i, j, idx

      INTEGER, ALLOCATABLE :: bufi_i(:), bufo_i(:,:)

      ALLOCATE(bufi_i(ish(1)), bufo_i(osh(1),osh(2)))
      CALL distrib_read_base(ncid, vname, bufi_i, iod(1)%basic_data_index)
!ICON_OMP PARALLEL DO COLLAPSE(2) PRIVATE(idx)
      DO i = 1, osh(2)
        DO j = 1, osh(1)
          idx = MERGE(idx_1d(j,i), ish(1), idx_1d(j,i) .LE. ish(1))
          bufo_i(j,i) = bufi_i(idx)
        END DO
      END DO
      DO i = 1, SIZE(iod)
        CALL exchange_data( &
          p_pat=iod(i)%pat, lacc=.FALSE., recv=vd(i)%p, send=bufo_i)
      END DO
    END SUBROUTINE read_multi_var_2dint

    SUBROUTINE read_multi_var_2ddp(vd)
      TYPE(t_ptr_2d_dp), INTENT(INOUT) :: vd(:)
      INTEGER :: i, j, idx

      REAL(dp), ALLOCATABLE :: bufi_d(:), bufo_d(:,:)

      ALLOCATE(bufi_d(ish(1)), bufo_d(osh(1),osh(2)))
      CALL distrib_read_base(ncid, vname, bufi_d, iod(1)%basic_data_index)
!ICON_OMP PARALLEL DO COLLAPSE(2) PRIVATE(idx)
      DO i = 1, osh(2)
        DO j = 1, osh(1)
          idx = MERGE(idx_1d(j,i), ish(1), idx_1d(j,i) .LE. ish(1))
          bufo_d(j,i) = bufi_d(idx)
        END DO
      END DO
      DO i = 1, SIZE(iod)
        CALL exchange_data( &
          p_pat=iod(i)%pat, lacc=.FALSE., recv=vd(i)%p, send=bufo_d)
      END DO
    END SUBROUTINE read_multi_var_2ddp

    SUBROUTINE read_multi_var_2dsp(vd)
      TYPE(t_ptr_2d_sp), INTENT(INOUT) :: vd(:)
      INTEGER :: i, j, idx

      REAL(sp), ALLOCATABLE :: bufi_s(:), bufo_s(:,:)

      ALLOCATE(bufi_s(ish(1)), bufo_s(osh(1),osh(2)))
      CALL distrib_read_base(ncid, vname, bufi_s, iod(1)%basic_data_index)
!ICON_OMP PARALLEL DO COLLAPSE(2) PRIVATE(idx)
      DO i = 1, osh(2)
        DO j = 1, osh(1)
          idx = MERGE(idx_1d(j,i), ish(1), idx_1d(j,i) .LE. ish(1))
          bufo_s(j,i) = bufi_s(idx)
        END DO
      END DO
      DO i = 1, SIZE(iod)
        CALL exchange_data( &
          p_pat=iod(i)%pat, lacc=.FALSE., recv=vd(i)%p, send=bufo_s)
      END DO
    END SUBROUTINE read_multi_var_2dsp

    SUBROUTINE read_multi_var_3dint(vd, o)
      TYPE(t_ptr_3d_int), INTENT(INOUT) :: vd(:)
      INTEGER, INTENT(IN) :: o
      INTEGER :: i, j, k, idx

      INTEGER, ALLOCATABLE :: bufi_i(:,:), bufo_i(:,:,:)

      ALLOCATE(bufi_i(ish(1),ish(2)), bufo_i(osh(1),osh(2),osh(3)))
      CALL distrib_read_base( &
        ncid, vname, bufi_i, iod(1)%basic_data_index, start_ext_dim)
      IF (o .EQ. idx_blk_time) THEN
!ICON_OMP PARALLEL DO COLLAPSE(3) PRIVATE(idx)
        DO i = 1, osh(3)
          DO j = 1, osh(2)
            DO k = 1, osh(1)
              idx = MERGE(idx_1d(k,j), ish(1), idx_1d(k,j) .LE. ish(1))
              bufo_i(k,j,i) = bufi_i(idx,i)
            END DO
          END DO
        END DO
      ELSE IF(o .EQ. idx_lvl_blk) THEN
!ICON_OMP PARALLEL DO COLLAPSE(3) PRIVATE(idx)
        DO i = 1, osh(3)
          DO j = 1, osh(2)
            DO k = 1, osh(1)
              idx = MERGE(idx_1d(k,i), ish(1), idx_1d(k,i) .LE. ish(1))
              bufo_i(k,j,i) = bufi_i(idx,j)
            END DO
          END DO
        END DO
      END IF
      DO i = 1, SIZE(iod)
        IF (o .EQ. idx_blk_time) THEN
          DO j = 1, ish(2)
            CALL exchange_data( &
              p_pat=iod(i)%pat, lacc=.FALSE., &
              recv=vd(i)%p(:,:,j), send=bufo_i(:,:,j))
          END DO
        ELSE IF(o .EQ. idx_lvl_blk) THEN
          CALL exchange_data( &
            p_pat=iod(i)%pat, lacc=.FALSE., recv=vd(i)%p, send=bufo_i)
        END IF
      END DO
    END SUBROUTINE read_multi_var_3dint

    SUBROUTINE read_multi_var_3ddp(vd, o)
      TYPE(t_ptr_3d_dp), INTENT(INOUT) :: vd(:)
      INTEGER, INTENT(IN) :: o
      INTEGER :: i, j, k, idx

      REAL(dp), ALLOCATABLE :: bufi_d(:,:), bufo_d(:,:,:)

      ALLOCATE(bufi_d(ish(1),ish(2)), bufo_d(osh(1),osh(2),osh(3)))
      CALL distrib_read_base( &
        ncid, vname, bufi_d, iod(1)%basic_data_index, start_ext_dim)
      IF (o .EQ. idx_blk_time) THEN
!ICON_OMP PARALLEL DO COLLAPSE(3) PRIVATE(idx)
        DO i = 1, osh(3)
          DO j = 1, osh(2)
            DO k = 1, osh(1)
              idx = MERGE(idx_1d(k,j), ish(1), idx_1d(k,j) .LE. ish(1))
              bufo_d(k,j,i) = bufi_d(idx,i)
            END DO
          END DO
        END DO
      ELSE IF(o .EQ. idx_lvl_blk) THEN
!ICON_OMP PARALLEL DO COLLAPSE(3) PRIVATE(idx)
        DO i = 1, osh(3)
          DO j = 1, osh(2)
            DO k = 1, osh(1)
              idx = MERGE(idx_1d(k,i), ish(1), idx_1d(k,i) .LE. ish(1))
              bufo_d(k,j,i) = bufi_d(idx,j)
            END DO
          END DO
        END DO
      END IF
      DO i = 1, SIZE(iod)
        IF (o .EQ. idx_blk_time) THEN
          DO j = 1, ish(2)
            CALL exchange_data( &
              p_pat=iod(i)%pat, lacc=.FALSE., &
              recv=vd(i)%p(:,:,j), send=bufo_d(:,:,j))
          END DO
        ELSE IF(o .EQ. idx_lvl_blk) THEN
          CALL exchange_data( &
            p_pat=iod(i)%pat, lacc=.FALSE., recv=vd(i)%p, send=bufo_d)
        END IF
      END DO
    END SUBROUTINE read_multi_var_3ddp

    SUBROUTINE read_multi_var_3dsp(vd, o)
      TYPE(t_ptr_3d_sp), INTENT(INOUT) :: vd(:)
      INTEGER, INTENT(IN) :: o
      INTEGER :: i, j, k, idx

      REAL(sp), ALLOCATABLE :: bufi_s(:,:), bufo_s(:,:,:)

      ALLOCATE(bufi_s(ish(1),ish(2)), bufo_s(osh(1),osh(2),osh(3)))
      CALL distrib_read_base( &
        ncid, vname, bufi_s, iod(1)%basic_data_index, start_ext_dim)
      IF (o .EQ. idx_blk_time) THEN
!ICON_OMP PARALLEL DO COLLAPSE(3) PRIVATE(idx)
        DO i = 1, osh(3)
          DO j = 1, osh(2)
            DO k = 1, osh(1)
              idx = MERGE(idx_1d(k,j), ish(1), idx_1d(k,j) .LE. ish(1))
              bufo_s(k,j,i) = bufi_s(idx,i)
            END DO
          END DO
        END DO
      ELSE IF(o .EQ. idx_lvl_blk) THEN
!ICON_OMP PARALLEL DO COLLAPSE(3) PRIVATE(idx)
        DO i = 1, osh(3)
          DO j = 1, osh(2)
            DO k = 1, osh(1)
              idx = MERGE(idx_1d(k,i), ish(1), idx_1d(k,i) .LE. ish(1))
              bufo_s(k,j,i) = bufi_s(idx,j)
            END DO
          END DO
        END DO
      END IF
      DO i = 1, SIZE(iod)
        IF (o .EQ. idx_blk_time) THEN
          DO j = 1, ish(2)
            CALL exchange_data( &
              p_pat=iod(i)%pat, lacc=.FALSE., &
              recv=vd(i)%p(:,:,j), send=bufo_s(:,:,j))
          END DO
        ELSE IF(o .EQ. idx_lvl_blk) THEN
          CALL exchange_data( &
            p_pat=iod(i)%pat, lacc=.FALSE., recv=vd(i)%p, send=bufo_s)
        END IF
      END DO
    END SUBROUTINE read_multi_var_3dsp

    SUBROUTINE read_multi_var_4dint(vd)
      TYPE(t_ptr_4d_int), INTENT(INOUT) :: vd(:)
      INTEGER :: i, j, k, l, idx

      INTEGER, ALLOCATABLE :: bufi_i(:,:,:), bufo_i(:,:,:,:)

      ALLOCATE(bufi_i(ish(1),ish(2),ish(3)), bufo_i(osh(1),osh(2),osh(3),osh(4)))
      CALL distrib_read_base( &
        ncid, vname, bufi_i, iod(1)%basic_data_index, start_ext_dim)
!ICON_OMP PARALLEL DO COLLAPSE(4) PRIVATE(idx)
      DO i = 1, osh(4)
        DO j = 1, osh(3)
          DO k = 1, osh(2)
            DO l = 1, osh(1)
              idx = MERGE(idx_1d(l,j), ish(1), idx_1d(l,j) .LE. ish(1))
              bufo_i(l,k,j,i) = bufi_i(idx,k,i)
            END DO
          END DO
        END DO
      END DO
      DO i = 1, SIZE(iod)
        DO j = 1, ish(3)
          CALL exchange_data( &
            p_pat=iod(i)%pat, lacc=.FALSE., &
            recv=vd(i)%p(:,:,:,j), send=bufo_i(:,:,:,j))
        END DO
      END DO
    END SUBROUTINE read_multi_var_4dint

    SUBROUTINE read_multi_var_4ddp(vd)
      TYPE(t_ptr_4d_dp), INTENT(INOUT) :: vd(:)
      INTEGER :: i, j, k, l, idx

      REAL(dp), ALLOCATABLE :: bufi_d(:,:,:), bufo_d(:,:,:,:)

      ALLOCATE(bufi_d(ish(1),ish(2),ish(3)), bufo_d(osh(1),osh(2),osh(3),osh(4)))
      CALL distrib_read_base( &
        ncid, vname, bufi_d, iod(1)%basic_data_index, start_ext_dim)
!ICON_OMP PARALLEL DO COLLAPSE(4) PRIVATE(idx)
      DO i = 1, osh(4)
        DO j = 1, osh(3)
          DO k = 1, osh(2)
            DO l = 1, osh(1)
              idx = MERGE(idx_1d(l,j), ish(1), idx_1d(l,j) .LE. ish(1))
              bufo_d(l,k,j,i) = bufi_d(idx,k,i)
            END DO
          END DO
        END DO
      END DO
      DO i = 1, SIZE(iod)
        DO j = 1, ish(3)
          CALL exchange_data( &
            p_pat=iod(i)%pat, lacc=.FALSE., &
            recv=vd(i)%p(:,:,:,j), send=bufo_d(:,:,:,j))
        END DO
      END DO
    END SUBROUTINE read_multi_var_4ddp

    SUBROUTINE read_multi_var_4dsp(vd)
      TYPE(t_ptr_4d_sp), INTENT(INOUT) :: vd(:)
      INTEGER :: i, j, k, l, idx

      REAL(sp), ALLOCATABLE :: bufi_s(:,:,:), bufo_s(:,:,:,:)

      ALLOCATE(bufi_s(ish(1),ish(2),ish(3)), bufo_s(osh(1),osh(2),osh(3),osh(4)))
      CALL distrib_read_base( &
        ncid, vname, bufi_s, iod(1)%basic_data_index, start_ext_dim)
!ICON_OMP PARALLEL DO COLLAPSE(4) PRIVATE(idx)
      DO i = 1, osh(4)
        DO j = 1, osh(3)
          DO k = 1, osh(2)
            DO l = 1, osh(1)
              idx = MERGE(idx_1d(l,j), ish(1), idx_1d(l,j) .LE. ish(1))
              bufo_s(l,k,j,i) = bufi_s(idx,k,i)
            END DO
          END DO
        END DO
      END DO
      DO i = 1, SIZE(iod)
        DO j = 1, ish(3)
          CALL exchange_data( &
            p_pat=iod(i)%pat, lacc=.FALSE., &
            recv=vd(i)%p(:,:,:,j), send=bufo_s(:,:,:,j))
        END DO
      END DO
    END SUBROUTINE read_multi_var_4dsp
  END SUBROUTINE distrib_read

END MODULE mo_read_netcdf_distributed
