! ICON
!
! ---------------------------------------------------------------
! Copyright (C) 2004-2025, DWD, MPI-M, DKRZ, KIT, ETH, MeteoSwiss
! Contact information: icon-model.org
!
! See AUTHORS.TXT for a list of authors
! See LICENSES/ for license information
! SPDX-License-Identifier: BSD-3-Clause
! ---------------------------------------------------------------

! This module provides methods for reading distributed data from a
! NetCDF file in a distributed way. It only supports user decompositions
! that contains a single contiguous global index range.
! Its primary application is this initial read of grid data in read_pre_patch.

#include "omp_definitions.inc"
! -----------------------------------------------------------------------------
! MODULE: mo_read_netcdf_distributed_cont
!
! Purpose
! -------
! Provide a reusable, distributed NetCDF read facility. The module implements:
!  - setup and usage of redistribution pattern from io decomposition
!    generated by mo_read_netcdf_distributed_base into the user decomposition
!
! Design overview
! ---------------
! * Read pattern:
!     1. Reading of data into a compact local buffer using
!        mo_read_netcdf_distributed_base
!     2. Use MPI_Alltoallv to redistribute data into the user decomposition.
!
! -----------------------------------------------------------------------------

MODULE mo_read_netcdf_distributed_cont

  USE mo_kind, ONLY: dp, sp
  USE mo_exception, ONLY: finish, message
  USE mo_mpi, ONLY: p_n_work, p_pe_work, p_bcast, p_comm_work, p_max, p_alltoallv
  USE ppm_extents, ONLY: extent, ASSIGNMENT(=), extent_intersect
  USE mo_decomposition_tools, ONLY: t_glb2loc_index_lookup, &
    & init_glb2loc_index_lookup, set_inner_glb_index, &
    & deallocate_glb2loc_index_lookup, uniform_partition, &
    & partidx_of_elem_uniform_deco
  USE mo_communication, ONLY: t_comm_pattern, exchange_data, &
    & delete_comm_pattern
  USE mo_parallel_config, ONLY: nproma, idx_1d
  USE mo_communication_factory, ONLY: setup_comm_pattern
  USE fortran_support, ONLY: t_ptr_2d_dp, t_ptr_2d_int, t_ptr_2d_sp, &
    & t_ptr_3d_dp, t_ptr_3d_int, t_ptr_3d_sp, t_ptr_4d_dp, t_ptr_4d_int, &
    & t_ptr_4d_sp
  USE mo_read_netcdf_types, ONLY: t_distrib_read_data
  USE mo_read_netcdf_distributed_base, ONLY: &
    & distrib_nf_open_cont => distrib_nf_open_base, &
    & distrib_nf_close_cont => distrib_nf_close_base, &
    & distrib_nf_inq_varexists_cont => distrib_nf_inq_varexists_base, &
    & distrib_nf_inq_attexists_cont => distrib_nf_inq_attexists_base, &
    & distrib_nf_inq_dimlen_cont => distrib_nf_inq_dimlen_base, &
    & distrib_inq_var_dims_cont => distrib_inq_var_dims_base, &
    & distrib_nf_get_att_cont => distrib_nf_get_att_base, &
    & distrib_read_root_cont => distrib_read_root_base, &
    & distrib_read_get_owner, distrib_read_get_decomp, &
    & setup_distrib_read_base, delete_distrib_read_base, &
    & distrib_read_base, distrib_read_get_alltoallv_args

  IMPLICIT NONE
  PRIVATE

  CHARACTER(*), PARAMETER :: modname = 'mo_read_netcdf_distributed_cont'

  PUBLIC :: distrib_read_cont
  PUBLIC :: distrib_read_root_cont
  PUBLIC :: distrib_nf_open_cont
  PUBLIC :: distrib_nf_inq_varexists_cont
  PUBLIC :: distrib_nf_inq_attexists_cont
  PUBLIC :: distrib_nf_inq_dimlen_cont
  PUBLIC :: distrib_nf_close_cont
  PUBLIC :: distrib_nf_get_att_cont
  PUBLIC :: setup_distrib_read_cont
  PUBLIC :: delete_distrib_read_cont
  PUBLIC :: t_distrib_read_data_cont
  PUBLIC :: distrib_inq_var_dims_cont

  TYPE t_distrib_read_data_cont
    INTEGER :: basic_data_index = -1
    TYPE(extent) :: local_chunk
    INTEGER, ALLOCATABLE :: sendcounts(:)
    INTEGER, ALLOCATABLE :: sdispls(:)
    INTEGER, ALLOCATABLE :: recvcounts(:)
    INTEGER, ALLOCATABLE :: rdispls(:)
  END TYPE t_distrib_read_data_cont

  ! -------------------------------------------------------------------
  ! Reads a 1D/2D INT/FLOAT/DOUBLE array from file
  !
  ! Inputs:
  !  - ncid: NetCDF file id on IO ranks, -1 on non-IO ranks
  !          (returned by distrib_nf_open_base)
  !  - vname: variable name
  !  - buffer: 1D/2D INT/FLOAT/DOUBLE buffer
  !  - io_data: valid IO data structure returned by setup_distrib_read_cont
  !
  ! Optional Inputs:
  !  - edim: size of second (extra) dimension (in 2D case)
  INTERFACE distrib_read_cont
    MODULE PROCEDURE distrib_read_cont_1D_int
    MODULE PROCEDURE distrib_read_cont_2D_int
    MODULE PROCEDURE distrib_read_cont_1D_sp
    MODULE PROCEDURE distrib_read_cont_2D_sp
    MODULE PROCEDURE distrib_read_cont_1D_dp
    MODULE PROCEDURE distrib_read_cont_2D_dp
  END INTERFACE distrib_read_cont

CONTAINS

  ! -------------------------------------------
  ! setup_distrib_read_cont(n_g, local_chunk, io_data)
  ! -------------------------------------------
  ! Prepare data structures and communication pattern for distributed reads of
  ! a global 1-D array of length n_g (e.g. global number of cells).
  !
  ! Inputs:
  !  - n_g: length of the global array
  !  - local_chunk: contiguous chunk of global indices of the points locally
  !                 stored on this process (may be empty)
  !
  ! Outputs / inout:
  !  - io_data: t_distrib_read_data_cont to be used by distrib_read_cont
  SUBROUTINE setup_distrib_read_cont(n_g, local_chunk, io_data)
    INTEGER, INTENT(in) :: n_g !< global array size
    TYPE(extent),INTENT(in) :: local_chunk !< description of locally stored
                                           !< elements (is a contiguous
                                           !< chunk of global indices in the
                                           !< range of [1;n_g]
    TYPE(t_distrib_read_data_cont), INTENT(inout) :: io_data

    ! setup basic read data
    CALL setup_distrib_read_base(n_g, io_data%basic_data_index)

    ! generate alltoallv arguments for redistribution from IO to
    ! user decomposition
    CALL distrib_read_get_alltoallv_args( &
      io_data%basic_data_index, local_chunk, &
      io_data%sendcounts, io_data%sdispls, io_data%recvcounts, io_data%rdispls)

    io_data%local_chunk = local_chunk

  END SUBROUTINE setup_distrib_read_cont

  !-----------------------------
  ! delete_distrib_read_cont(io_data)
  ! ----------------------------
  ! Deregister and free resources associated with io_data created by
  ! setup_distrib_read_cont.
  SUBROUTINE delete_distrib_read_cont(io_data)
    TYPE(t_distrib_read_data_cont), INTENT(inout) :: io_data

    DEALLOCATE( &
      io_data%sendcounts, io_data%sdispls, io_data%recvcounts, io_data%rdispls)
    CALL delete_distrib_read_base(io_data%basic_data_index)

  END SUBROUTINE delete_distrib_read_cont

  ! ----------------------------------------------------------------------------
  ! Read routines for  1D/2D INT/FLOAT/DOUBLE arrays
  ! ----------------------------------------------------------------------------

  SUBROUTINE distrib_read_cont_1D_int( &
    ncid, vname, out_buffer, io_data)
    INTEGER, INTENT(IN) :: ncid
    CHARACTER(*), INTENT(IN) :: vname
    INTEGER, INTENT(INOUT) :: out_buffer(:)
    TYPE(t_distrib_read_data_cont), INTENT(IN) :: io_data

    INTEGER :: read_buffer_size
    INTEGER, ALLOCATABLE :: read_buffer(:)

    CHARACTER(*), PARAMETER :: &
      routine = modname//'::distrib_read_cont_1D_int'

    ! allocate read buffers
    read_buffer_size = &
      get_read_buffer_size_1D(routine, io_data, SIZE(out_buffer))
    ALLOCATE(read_buffer(read_buffer_size))

    ! read data from file into the IO decomposition
    CALL distrib_read_base(ncid, vname, read_buffer, io_data%basic_data_index)

    ! redistribute data into user decomposition
    CALL p_alltoallv( &
      read_buffer, io_data%sendcounts, io_data%sdispls, &
      out_buffer, io_data%recvcounts, io_data%rdispls, p_comm_work)

  END SUBROUTINE distrib_read_cont_1D_int

  SUBROUTINE distrib_read_cont_2D_int( &
    ncid, vname, out_buffer, io_data, opt_edim)
    INTEGER, INTENT(IN) :: ncid
    CHARACTER(*), INTENT(IN) :: vname
    INTEGER, INTENT(INOUT) :: out_buffer(:,:)
    TYPE(t_distrib_read_data_cont), INTENT(IN) :: io_data
    INTEGER, OPTIONAL, INTENT(IN) :: opt_edim

    INTEGER :: edim, i
    INTEGER :: read_buffer_size(2)
    INTEGER, ALLOCATABLE :: read_buffer(:,:)

    CHARACTER(*), PARAMETER :: &
      routine = modname//'::distrib_read_cont_2D_int'

    ! allocate read buffers
    read_buffer_size = &
      get_read_buffer_size_2D( &
        routine, io_data, SHAPE(out_buffer), edim, opt_edim)
    ALLOCATE(read_buffer(read_buffer_size(1), read_buffer_size(2)))

    ! read data from file into the IO decomposition
    CALL distrib_read_base( &
      ncid, vname, read_buffer(:,1:edim), io_data%basic_data_index)

    ! redistribute data into user decomposition
    DO i = 1, edim
      CALL p_alltoallv( &
        read_buffer(:,i), io_data%sendcounts, io_data%sdispls, &
        out_buffer(:,i), io_data%recvcounts, io_data%rdispls, p_comm_work)
    END DO

  END SUBROUTINE distrib_read_cont_2D_int

  SUBROUTINE distrib_read_cont_1D_sp( &
    ncid, vname, out_buffer, io_data)
    INTEGER, INTENT(IN) :: ncid
    CHARACTER(*), INTENT(IN) :: vname
    REAL(sp), INTENT(INOUT) :: out_buffer(:)
    TYPE(t_distrib_read_data_cont), INTENT(IN) :: io_data

    INTEGER :: read_buffer_size
    REAL(sp), ALLOCATABLE :: read_buffer(:)

    CHARACTER(*), PARAMETER :: &
      routine = modname//'::distrib_read_cont_1D_sp'

    ! allocate read buffers
    read_buffer_size = &
      get_read_buffer_size_1D(routine, io_data, SIZE(out_buffer))
    ALLOCATE(read_buffer(read_buffer_size))

    ! read data from file into the IO decomposition
    CALL distrib_read_base(ncid, vname, read_buffer, io_data%basic_data_index)

    ! redistribute data into user decomposition
    CALL p_alltoallv( &
      read_buffer, io_data%sendcounts, io_data%sdispls, &
      out_buffer, io_data%recvcounts, io_data%rdispls, p_comm_work)

  END SUBROUTINE distrib_read_cont_1D_sp

  SUBROUTINE distrib_read_cont_2D_sp( &
    ncid, vname, out_buffer, io_data, opt_edim)
    INTEGER, INTENT(IN) :: ncid
    CHARACTER(*), INTENT(IN) :: vname
    REAL(sp), INTENT(INOUT) :: out_buffer(:,:)
    TYPE(t_distrib_read_data_cont), INTENT(IN) :: io_data
    INTEGER, OPTIONAL, INTENT(IN) :: opt_edim

    INTEGER :: edim, i
    INTEGER :: read_buffer_size(2)
    REAL(sp), ALLOCATABLE :: read_buffer(:,:)

    CHARACTER(*), PARAMETER :: &
      routine = modname//'::distrib_read_cont_2D_sp'

    ! allocate read buffers
    read_buffer_size = &
      get_read_buffer_size_2D( &
        routine, io_data, SHAPE(out_buffer), edim, opt_edim)
    ALLOCATE(read_buffer(read_buffer_size(1), read_buffer_size(2)))

    ! read data from file into the IO decomposition
    CALL distrib_read_base( &
      ncid, vname, read_buffer(:,1:edim), io_data%basic_data_index)

    ! redistribute data into user decomposition
    DO i = 1, edim
      CALL p_alltoallv( &
        read_buffer(:,i), io_data%sendcounts, io_data%sdispls, &
        out_buffer(:,i), io_data%recvcounts, io_data%rdispls, p_comm_work)
    END DO

  END SUBROUTINE distrib_read_cont_2D_sp

  SUBROUTINE distrib_read_cont_1D_dp( &
    ncid, vname, out_buffer, io_data)
    INTEGER, INTENT(IN) :: ncid
    CHARACTER(*), INTENT(IN) :: vname
    REAL(dp), INTENT(INOUT) :: out_buffer(:)
    TYPE(t_distrib_read_data_cont), INTENT(IN) :: io_data

    INTEGER :: read_buffer_size
    REAL(dp), ALLOCATABLE :: read_buffer(:)

    CHARACTER(*), PARAMETER :: &
      routine = modname//'::distrib_read_cont_1D_dp'

    ! allocate read buffers
    read_buffer_size = &
      get_read_buffer_size_1D(routine, io_data, SIZE(out_buffer))
    ALLOCATE(read_buffer(read_buffer_size))

    ! read data from file into the IO decomposition
    CALL distrib_read_base(ncid, vname, read_buffer, io_data%basic_data_index)

    ! redistribute data into user decomposition
    CALL p_alltoallv( &
      read_buffer, io_data%sendcounts, io_data%sdispls, &
      out_buffer, io_data%recvcounts, io_data%rdispls, p_comm_work)

  END SUBROUTINE distrib_read_cont_1D_dp

  SUBROUTINE distrib_read_cont_2D_dp( &
    ncid, vname, read_buffer, out_buffer, io_data, opt_edim)
    INTEGER, INTENT(IN) :: ncid
    CHARACTER(*), INTENT(IN) :: vname
    REAL(dp), INTENT(INOUT) :: out_buffer(:,:)
    TYPE(t_distrib_read_data_cont), INTENT(IN) :: io_data
    INTEGER, OPTIONAL, INTENT(IN) :: opt_edim

    INTEGER :: edim, i
    INTEGER :: read_buffer_size(2)
    REAL(dp), ALLOCATABLE :: read_buffer(:,:)

    CHARACTER(*), PARAMETER :: &
      routine = modname//'::distrib_read_cont_2D_dp'

    ! allocate read buffers
    read_buffer_size = &
      get_read_buffer_size_2D( &
        routine, io_data, SHAPE(out_buffer), edim, opt_edim)
    ALLOCATE(read_buffer(read_buffer_size(1), read_buffer_size(2)))

    ! read data from file into the IO decomposition
    CALL distrib_read_base( &
      ncid, vname, read_buffer(:,1:edim), io_data%basic_data_index)

    ! redistribute data into user decomposition
    DO i = 1, edim
      CALL p_alltoallv( &
        read_buffer(:,i), io_data%sendcounts, io_data%sdispls, &
        out_buffer(:,i), io_data%recvcounts, io_data%rdispls, p_comm_work)
    END DO

  END SUBROUTINE distrib_read_cont_2D_dp

  !-----------------------------------------------------------------------------
  ! Some utility routines
  !-----------------------------------------------------------------------------

  FUNCTION get_read_buffer_size_1D(routine, io_data, out_buffer_size)
    CHARACTER(*), INTENT(IN) :: routine
    TYPE(t_distrib_read_data_cont), INTENT(IN) :: io_data
    INTEGER, INTENT(IN) :: out_buffer_size

    INTEGER :: get_read_buffer_size_1D

    TYPE(extent) :: io_chunk
    INTEGER :: io_chunk_size

    io_chunk = distrib_read_get_decomp(io_data%basic_data_index)
    io_chunk_size = io_chunk%size
    get_read_buffer_size_1D = io_chunk_size
    IF (out_buffer_size /= io_data%local_chunk%size) &
      CALL finish(routine, "mismatching out buffer size")

  END FUNCTION get_read_buffer_size_1D

  FUNCTION get_read_buffer_size_2D( &
    routine, io_data, out_buffer_shape, edim, opt_edim)
    CHARACTER(*), INTENT(IN) :: routine
    TYPE(t_distrib_read_data_cont), INTENT(IN) :: io_data
    INTEGER, INTENT(IN) :: out_buffer_shape(2)
    INTEGER, INTENT(OUT) :: edim
    INTEGER, OPTIONAL, INTENT(IN) :: opt_edim

    INTEGER :: get_read_buffer_size_2D(2)

    get_read_buffer_size_2D(1) =  &
      get_read_buffer_size_1D( &
        routine, io_data, out_buffer_shape(1))

    IF (PRESENT(opt_edim)) THEN
      edim = opt_edim
      IF (out_buffer_shape(2) < opt_edim) &
        CALL finish(routine, "2nd dimension of buffer is too small")
    ELSE
      edim = out_buffer_shape(2)
    END IF
    get_read_buffer_size_2D(2) = edim

  END FUNCTION get_read_buffer_size_2D

END MODULE mo_read_netcdf_distributed_cont
