#!/bin/bash

# ICON
#
# ------------------------------------------
# Copyright (C) 2004-2026, DWD, MPI-M, DKRZ, KIT, ETH, MeteoSwiss
# Contact information: icon-model.org
# See AUTHORS.TXT for a list of authors
# See LICENSES/ for license information
# SPDX-License-Identifier: BSD-3-Clause
# ------------------------------------------

# abort on error
set -euo pipefail

cd $(dirname "${BASH_SOURCE[0]}")
set -x
addexp="./addexp"
#############################################################################
##
## create ocean list
##
#############################################################################
listname=oes-ref
./rmlist $listname

./create_all_builders $listname
#  de-activate builders - must be commented if lists for debugging are switched on
./set_builder_flags Inactive --builders "$(./lslist $listname --builders-only)" --list $listname

#-----------------------------------------------------------
# OES
LEVANTE_OCE_BUILDERS='levante_gcc levante_gcc_hybrid levante_intel levante_intel_hybrid levante_nag'
./set_builder_flags Active --builders "${LEVANTE_OCE_BUILDERS}" --list $listname

# add omip binary-identical test on levante
$addexp checksuite.ocean_internal/omip/exp.test_ocean_omip_10days \
--builders "${LEVANTE_OCE_BUILDERS}" --runflags "cpu_time=00:30:00 queue=shared,compute memory=32G ntasks=16" --list $listname
$addexp checksuite.ocean_internal/omip/exp.test_ocean_zstar_omip_10days \
--builders "${LEVANTE_OCE_BUILDERS}" --runflags "cpu_time=00:30:00 queue=shared,compute memory=32G ntasks=16" --list $listname
$addexp checksuite.ocean_internal/hamocc/exp.test_hamocc_omip_10days       \
--builders "${LEVANTE_OCE_BUILDERS}" --runflags "cpu_time=00:30:00 queue=shared,compute memory=32G ntasks=16" --list $listname

$addexp checksuite.ocean_internal/omip/pp.refgen_test_ocean_omip_10days        --builders "${LEVANTE_OCE_BUILDERS}" --list $listname
$addexp checksuite.ocean_internal/omip/pp.refgen_test_ocean_zstar_omip_10days  --builders "${LEVANTE_OCE_BUILDERS}" --list $listname
$addexp checksuite.ocean_internal/hamocc/pp.refgen_test_hamocc_omip_10days     --builders "${LEVANTE_OCE_BUILDERS}" --list $listname



./adddep --from-experiment checksuite.ocean_internal/omip/pp.refgen_test_ocean_omip_10days \
         --to-experiment checksuite.ocean_internal/omip/exp.test_ocean_omip_10days \
	 --builders "${LEVANTE_OCE_BUILDERS}" --list $listname
./adddep --from-experiment checksuite.ocean_internal/omip/pp.refgen_test_ocean_zstar_omip_10days \
         --to-experiment checksuite.ocean_internal/omip/exp.test_ocean_zstar_omip_10days \
	 --builders "${LEVANTE_OCE_BUILDERS}" --list $listname
./adddep --from-experiment checksuite.ocean_internal/hamocc/pp.refgen_test_hamocc_omip_10days \
         --to-experiment checksuite.ocean_internal/hamocc/exp.test_hamocc_omip_10days \
	 --builders "${LEVANTE_OCE_BUILDERS}" --list $listname
#-----------------------------------------------------------
#lets see the list
./lslist $listname
#-----------------------------------------------------------
