#!/bin/bash

# ICON
#
# ------------------------------------------
# Copyright (C) 2004-2026, DWD, MPI-M, DKRZ, KIT, ETH, MeteoSwiss
# Contact information: icon-model.org
# See AUTHORS.TXT for a list of authors
# See LICENSES/ for license information
# SPDX-License-Identifier: BSD-3-Clause
# ------------------------------------------

# ------------------------------------------
# Experiment list for builders configured with `--enable-single-precision` flag.
#
# ------------------------------------------

# abort on error
set -euo pipefail

cd $(dirname "${BASH_SOURCE[0]}")

addexp="./addexp"

#############################################################################
listname=single

./rmlist $listname

./create_all_builders $listname

#  de-activate builders - must be commented if lists for debugging are switched on
./set_builder_flags Inactive --builders "$(./lslist $listname --builders-only)" --list $listname

#############################################################################

# Activate all single-precision builders as build-only
SINGLE_PRECISION_BUILDERS="levante_gcc_sp levante_intel_hybrid_sp levante_nag_sp levante_gpu_nvhpc_sp lumi_cpu_sp mpimac_gcc_sp dwd_nec_sp"
./set_builder_flags build_only --builders "${SINGLE_PRECISION_BUILDERS}" --list $listname

#############################################################################

#lets see the list
./lslist $listname
