#! /usr/bin/env python3

# ICON
#
# ------------------------------------------
# Copyright (C) 2004-2026, DWD, MPI-M, DKRZ, KIT, ETH, MeteoSwiss
# Contact information: icon-model.org
# See AUTHORS.TXT for a list of authors
# See LICENSES/ for license information
# SPDX-License-Identifier: BSD-3-Clause
# ------------------------------------------

# -*- coding: utf-8 -*-
# ==============================================================================
# create an experiment list
# ==============================================================================

import pickle
import sys
from pathlib import Path

import click
from buildbot_config import BuildbotConfig
from icon_paths import buildbot_list_path, run_path


@click.command()
@click.argument("builder", type=str)
@click.option(
    "--list",
    "list_name",
    type=str,
    help="the buildbot configuration list",
    required=True,
)
def lsexperiments(builder, list_name):
    full_list_name = buildbot_list_path / list_name

    if Path(full_list_name).exists():
        thisList = BuildbotConfig.from_pickle(full_list_name)
    else:
        print("did not find experiment list {}".format(full_list_name))
        sys.exit(1)

    exp_list = thisList.list_experiments_by_builder(builder)

    for exp in exp_list:
        print(exp)


if __name__ == "__main__":
    lsexperiments()
