#!/bin/bash

# ICON
#
# ------------------------------------------
# Copyright (C) 2004-2026, DWD, MPI-M, DKRZ, KIT, ETH, MeteoSwiss
# Contact information: icon-model.org
# See AUTHORS.TXT for a list of authors
# See LICENSES/ for license information
# SPDX-License-Identifier: BSD-3-Clause
# ------------------------------------------

set -euo pipefail

MY_DIR=$(cd "$(dirname "$0")"; pwd)
# ICON_DIR=$(cd "${MY_DIR}/../../.."; pwd) # real relative path
ICON_DIR=$(cd "${MY_DIR}/.."; pwd) # relative path of the symlink created by buildbot in ./run

echo "  MY_DIR: ${MY_DIR}"
echo "ICON_DIR: ${ICON_DIR}"

VE_DIR="${ICON_DIR}/build/ve"
VH_DIR="${ICON_DIR}/build/vh"

for build_dir in ${VE_DIR} ${VH_DIR}; do
  echo "Run binary from ${build_dir} ..."
  echo "Hadley test"
  cd ${build_dir};
  ./make_runscripts atm_tracer_Hadley
  cd ./run
  ./exp.atm_tracer_Hadley.run

  echo "###########################################################################"
  echo "SYNC testbed"
  cd ${build_dir}/run
  ln -s checksuite.infrastructure/testbed/exp.icon-testbed_sync
  cd ${build_dir}
  ./make_runscripts icon-testbed_sync
  cd ./run
  ./exp.icon-testbed_sync.run
done
